// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"agents.mdx": () => import("../content/docs/agents.mdx?collection=docs"), "alerts.mdx": () => import("../content/docs/alerts.mdx?collection=docs"), "allocation.mdx": () => import("../content/docs/allocation.mdx?collection=docs"), "api-reference.mdx": () => import("../content/docs/api-reference.mdx?collection=docs"), "architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "chargeback.mdx": () => import("../content/docs/chargeback.mdx?collection=docs"), "cli.mdx": () => import("../content/docs/cli.mdx?collection=docs"), "comparison.mdx": () => import("../content/docs/comparison.mdx?collection=docs"), "compatibility.mdx": () => import("../content/docs/compatibility.mdx?collection=docs"), "concepts.mdx": () => import("../content/docs/concepts.mdx?collection=docs"), "crd-reference.mdx": () => import("../content/docs/crd-reference.mdx?collection=docs"), "deploy.mdx": () => import("../content/docs/deploy.mdx?collection=docs"), "faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "integrations/clouds.mdx": () => import("../content/docs/integrations/clouds.mdx?collection=docs"), "integrations/identity.mdx": () => import("../content/docs/integrations/identity.mdx?collection=docs"), "integrations/prometheus-grafana.mdx": () => import("../content/docs/integrations/prometheus-grafana.mdx?collection=docs"), "logs.mdx": () => import("../content/docs/logs.mdx?collection=docs"), "metrics-reference.mdx": () => import("../content/docs/metrics-reference.mdx?collection=docs"), "network.mdx": () => import("../content/docs/network.mdx?collection=docs"), "overview.mdx": () => import("../content/docs/overview.mdx?collection=docs"), "production.mdx": () => import("../content/docs/production.mdx?collection=docs"), "profiling.mdx": () => import("../content/docs/profiling.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "rightsizing.mdx": () => import("../content/docs/rightsizing.mdx?collection=docs"), "security.mdx": () => import("../content/docs/security.mdx?collection=docs"), "stack.mdx": () => import("../content/docs/stack.mdx?collection=docs"), "troubleshooting.mdx": () => import("../content/docs/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;