// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netflowFlowKey struct {
	_         structs.HostLayout
	Saddr     [16]uint8
	Daddr     [16]uint8
	Port      uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       [3]uint8
}

type netflowFlowVal struct {
	_       structs.HostLayout
	Bytes   uint64
	Packets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	netflowMapKhFlows         = "kh_flows"
	netflowMapKhNfErrors      = "kh_nf_errors"
	netflowProgKhFlowEgress   = "kh_flow_egress"
	netflowProgKhFlowIngress  = "kh_flow_ingress"
	netflowVarIncludeLoopback = "include_loopback"
)

// loadNetflow returns the embedded CollectionSpec for netflow.
func loadNetflow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetflowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netflow: %w", err)
	}

	return spec, err
}

// loadNetflowObjects loads netflow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netflowObjects
//	*netflowPrograms
//	*netflowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetflowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetflow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netflowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netflowSpecs struct {
	netflowProgramSpecs
	netflowMapSpecs
	netflowVariableSpecs
}

// netflowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netflowProgramSpecs struct {
	KhFlowEgress  *ebpf.ProgramSpec `ebpf:"kh_flow_egress"`
	KhFlowIngress *ebpf.ProgramSpec `ebpf:"kh_flow_ingress"`
}

// netflowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netflowMapSpecs struct {
	KhFlows    *ebpf.MapSpec `ebpf:"kh_flows"`
	KhNfErrors *ebpf.MapSpec `ebpf:"kh_nf_errors"`
}

// netflowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netflowVariableSpecs struct {
	IncludeLoopback *ebpf.VariableSpec `ebpf:"include_loopback"`
}

// netflowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type netflowObjects struct {
	netflowPrograms
	netflowMaps
	netflowVariables
}

func (o *netflowObjects) Close() error {
	return _NetflowClose(
		&o.netflowPrograms,
		&o.netflowMaps,
	)
}

// netflowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type netflowMaps struct {
	KhFlows    *ebpf.Map `ebpf:"kh_flows"`
	KhNfErrors *ebpf.Map `ebpf:"kh_nf_errors"`
}

func (m *netflowMaps) Close() error {
	return _NetflowClose(
		m.KhFlows,
		m.KhNfErrors,
	)
}

// netflowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type netflowVariables struct {
	IncludeLoopback *ebpf.Variable `ebpf:"include_loopback"`
}

// netflowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type netflowPrograms struct {
	KhFlowEgress  *ebpf.Program `ebpf:"kh_flow_egress"`
	KhFlowIngress *ebpf.Program `ebpf:"kh_flow_ingress"`
}

func (p *netflowPrograms) Close() error {
	return _NetflowClose(
		p.KhFlowEgress,
		p.KhFlowIngress,
	)
}

func _NetflowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netflow_bpfel.o
var _NetflowBytes []byte
