// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type profilerStackKey struct {
	_             structs.HostLayout
	CgroupId      uint64
	Tgid          uint32
	UserStackId   int32
	KernelStackId int32
	Pad           uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	profilerMapKhActive     = "kh_active"
	profilerMapKhCounts0    = "kh_counts0"
	profilerMapKhCounts1    = "kh_counts1"
	profilerMapKhProfErrors = "kh_prof_errors"
	profilerMapKhStacks0    = "kh_stacks0"
	profilerMapKhStacks1    = "kh_stacks1"
	profilerProgKhProfile   = "kh_profile"
	profilerVarSelfTgid     = "self_tgid"
)

// loadProfiler returns the embedded CollectionSpec for profiler.
func loadProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load profiler: %w", err)
	}

	return spec, err
}

// loadProfilerObjects loads profiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*profilerObjects
//	*profilerPrograms
//	*profilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProfilerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// profilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerSpecs struct {
	profilerProgramSpecs
	profilerMapSpecs
	profilerVariableSpecs
}

// profilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerProgramSpecs struct {
	KhProfile *ebpf.ProgramSpec `ebpf:"kh_profile"`
}

// profilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerMapSpecs struct {
	KhActive     *ebpf.MapSpec `ebpf:"kh_active"`
	KhCounts0    *ebpf.MapSpec `ebpf:"kh_counts0"`
	KhCounts1    *ebpf.MapSpec `ebpf:"kh_counts1"`
	KhProfErrors *ebpf.MapSpec `ebpf:"kh_prof_errors"`
	KhStacks0    *ebpf.MapSpec `ebpf:"kh_stacks0"`
	KhStacks1    *ebpf.MapSpec `ebpf:"kh_stacks1"`
}

// profilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerVariableSpecs struct {
	SelfTgid *ebpf.VariableSpec `ebpf:"self_tgid"`
}

// profilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerObjects struct {
	profilerPrograms
	profilerMaps
	profilerVariables
}

func (o *profilerObjects) Close() error {
	return _ProfilerClose(
		&o.profilerPrograms,
		&o.profilerMaps,
	)
}

// profilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerMaps struct {
	KhActive     *ebpf.Map `ebpf:"kh_active"`
	KhCounts0    *ebpf.Map `ebpf:"kh_counts0"`
	KhCounts1    *ebpf.Map `ebpf:"kh_counts1"`
	KhProfErrors *ebpf.Map `ebpf:"kh_prof_errors"`
	KhStacks0    *ebpf.Map `ebpf:"kh_stacks0"`
	KhStacks1    *ebpf.Map `ebpf:"kh_stacks1"`
}

func (m *profilerMaps) Close() error {
	return _ProfilerClose(
		m.KhActive,
		m.KhCounts0,
		m.KhCounts1,
		m.KhProfErrors,
		m.KhStacks0,
		m.KhStacks1,
	)
}

// profilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerVariables struct {
	SelfTgid *ebpf.Variable `ebpf:"self_tgid"`
}

// profilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerPrograms struct {
	KhProfile *ebpf.Program `ebpf:"kh_profile"`
}

func (p *profilerPrograms) Close() error {
	return _ProfilerClose(
		p.KhProfile,
	)
}

func _ProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed profiler_bpfel.o
var _ProfilerBytes []byte
