// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpretransFlowKey struct {
	_         structs.HostLayout
	Saddr     [16]uint8
	Daddr     [16]uint8
	Port      uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       [3]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpretransMapKhRetrans        = "kh_retrans"
	tcpretransMapKhRtErrors       = "kh_rt_errors"
	tcpretransProgKhTcpRetransmit = "kh_tcp_retransmit"
	tcpretransVarIncludeLoopback  = "include_loopback"
	tcpretransVarOffDaddrV6       = "off_daddr_v6"
	tcpretransVarOffDport         = "off_dport"
	tcpretransVarOffSaddrV6       = "off_saddr_v6"
	tcpretransVarOffSport         = "off_sport"
)

// loadTcpretrans returns the embedded CollectionSpec for tcpretrans.
func loadTcpretrans() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpretransBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpretrans: %w", err)
	}

	return spec, err
}

// loadTcpretransObjects loads tcpretrans and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpretransObjects
//	*tcpretransPrograms
//	*tcpretransMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpretransObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpretrans()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpretransSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransSpecs struct {
	tcpretransProgramSpecs
	tcpretransMapSpecs
	tcpretransVariableSpecs
}

// tcpretransProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransProgramSpecs struct {
	KhTcpRetransmit *ebpf.ProgramSpec `ebpf:"kh_tcp_retransmit"`
}

// tcpretransMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransMapSpecs struct {
	KhRetrans  *ebpf.MapSpec `ebpf:"kh_retrans"`
	KhRtErrors *ebpf.MapSpec `ebpf:"kh_rt_errors"`
}

// tcpretransVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransVariableSpecs struct {
	IncludeLoopback *ebpf.VariableSpec `ebpf:"include_loopback"`
	OffDaddrV6      *ebpf.VariableSpec `ebpf:"off_daddr_v6"`
	OffDport        *ebpf.VariableSpec `ebpf:"off_dport"`
	OffSaddrV6      *ebpf.VariableSpec `ebpf:"off_saddr_v6"`
	OffSport        *ebpf.VariableSpec `ebpf:"off_sport"`
}

// tcpretransObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransObjects struct {
	tcpretransPrograms
	tcpretransMaps
	tcpretransVariables
}

func (o *tcpretransObjects) Close() error {
	return _TcpretransClose(
		&o.tcpretransPrograms,
		&o.tcpretransMaps,
	)
}

// tcpretransMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransMaps struct {
	KhRetrans  *ebpf.Map `ebpf:"kh_retrans"`
	KhRtErrors *ebpf.Map `ebpf:"kh_rt_errors"`
}

func (m *tcpretransMaps) Close() error {
	return _TcpretransClose(
		m.KhRetrans,
		m.KhRtErrors,
	)
}

// tcpretransVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransVariables struct {
	IncludeLoopback *ebpf.Variable `ebpf:"include_loopback"`
	OffDaddrV6      *ebpf.Variable `ebpf:"off_daddr_v6"`
	OffDport        *ebpf.Variable `ebpf:"off_dport"`
	OffSaddrV6      *ebpf.Variable `ebpf:"off_saddr_v6"`
	OffSport        *ebpf.Variable `ebpf:"off_sport"`
}

// tcpretransPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransPrograms struct {
	KhTcpRetransmit *ebpf.Program `ebpf:"kh_tcp_retransmit"`
}

func (p *tcpretransPrograms) Close() error {
	return _TcpretransClose(
		p.KhTcpRetransmit,
	)
}

func _TcpretransClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpretrans_bpfel.o
var _TcpretransBytes []byte
