apiVersion: kubehero.kubehero.io/v1
kind: CeilingPolicy
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: ceilingpolicy-sample
spec:
  # TODO(user): Add fields here
