// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) KubeHero contributors

// RightsizingPolicy YAML for one recommendation. The dashboard never
// mutates a workload: it hands the operator a guarded CRD. Applying the
// YAML changes nothing either — the operator only patches requests once a
// human arms the policy (kubehero.kubehero.io/armed=true) and every guard
// passes (confidence, OOM history, rollout state, max change per day).
//
// RightsizingPolicy scopes by namespace, so "just this workload" is
// expressed as a namespace scope plus an `exclude` list of the other
// workloads we know about there. The comment block says so plainly.
//
// Pure + client-safe (the drawer regenerates it when the mode changes).

export type PolicyMode = "recommend" | "shadow" | "apply";

export type PolicyInput = {
  cluster: string;
  namespace: string;
  workload: string;
  container: string;
  window: string;
  headroomPct: number;
  replicas: number;
  /** Other workloads in the namespace (excluded from this policy). */
  siblings: string[];
  cpuRecommended: string;
  memRecommended: string;
  savingsUsdMonth: number;
};

const DNS1123 = /[^a-z0-9-]+/g;

/** DNS-1123 name from parts, ≤ 63 chars, no leading/trailing dash. */
export function policyName(namespace: string, workload: string): string {
  const raw = `rightsize-${namespace}-${workload}`.toLowerCase().replace(DNS1123, "-").replace(/-+/g, "-");
  return raw.slice(0, 63).replace(/^-+|-+$/g, "");
}

/** YAML-safe scalar: quote when the plain form would be ambiguous. */
export function yamlScalar(v: string): string {
  if (v === "" || /^[\s]|[\s]$|[:#{}\[\],&*!|>'"%@`]|^(true|false|null|yes|no|on|off|~|-?\d[\d.]*)$/i.test(v)) {
    return `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return v;
}

export function rightsizingPolicyYaml(p: PolicyInput, mode: PolicyMode = "apply"): string {
  const name = policyName(p.namespace, p.workload);
  const siblings = [...new Set(p.siblings.filter((s) => s && s !== p.workload))].sort().slice(0, 200);
  const modeNote: Record<PolicyMode, string> = {
    recommend: "# mode: recommend — the operator only writes recommendations into status.",
    shadow: "# mode: shadow — records what it WOULD change (status + audit), mutates nothing.",
    apply: "# mode: apply — patches requests, but only after a human arms the policy.",
  };
  const lines = [
    `# RightsizingPolicy generated by the KubeHero dashboard`,
    `#   target   ${p.cluster}/${p.namespace}/${p.workload} (container ${p.container})`,
    `#   proposal cpu ${p.cpuRecommended} · memory ${p.memRecommended} · saves ~$${Math.round(Math.max(0, p.savingsUsdMonth)).toLocaleString("en-US")}/mo`,
    `#`,
    modeNote[mode],
    `# Apply it to cluster ${p.cluster}:  kubectl apply -f ${name}.yaml`,
    ...(mode === "apply"
      ? [
          `# Nothing is mutated until you arm it (every change is audited and reversible):`,
          `#   kubectl -n kubehero-system annotate rightsizingpolicy ${name} kubehero.kubehero.io/armed=true`,
        ]
      : []),
    `# Scope is the whole namespace; \`exclude\` lists the other workloads`,
    `# KubeHero knows about there so this policy only touches ${p.workload}.`,
    `apiVersion: kubehero.kubehero.io/v1`,
    `kind: RightsizingPolicy`,
    `metadata:`,
    `  name: ${name}`,
    `  namespace: kubehero-system`,
    `  labels:`,
    `    app.kubernetes.io/managed-by: kubehero-dashboard`,
    `spec:`,
    `  scope:`,
    `    namespaceSelector:`,
    `      matchLabels:`,
    `        kubernetes.io/metadata.name: ${yamlScalar(p.namespace)}`,
    `  mode: ${mode}`,
  ];
  if (siblings.length > 0) {
    lines.push(`  exclude:`);
    for (const s of siblings) lines.push(`    - ${yamlScalar(s)}`);
  }
  lines.push(
    `  safety:`,
    `    observationWindow: ${yamlScalar(p.window)}`,
    `    p95HeadroomPct: ${Math.round(p.headroomPct)}`,
    `    maxChangePerDay: 1`,
  );
  if (p.replicas >= 2) lines.push(`    minReplicas: ${Math.min(p.replicas, 2)}`);
  return lines.join("\n") + "\n";
}
